server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: static_page_route
          uri: lb://STATICHTMLSERVICE
          predicates:
            - Path=/
            - Method=GET
        - id: static_page_route
          uri: lb://STATICHTMLSERVICE
          predicates:
            - Path=/static/**
        - id: static_page_route
          uri: lb://STATICHTMLSERVICE
          predicates:
            - Path=/src/**
        - id: token
          uri: lb://TOKENSERVICE
          predicates:
            - Path=/token/**
        - id: edit
          uri: lb://EDITSERVICE
          predicates:
            - Path=/edit/**
        - id: source
          uri: lb://SOURCESERVICE
          predicates:
            - Path=/source/**
        - id: login
          uri: lb://LOGSERVICE
          predicates:
            - Path=/login/**
        - id: mainpage
          uri: lb://MAINPAGESERVICE
          predicates:
            - Path=/mainpage/**
        - id: private
          uri: lb://PRIVATEPAGESERVICE
          predicates:
            - Path=/private/**
        - id: audit
          uri: lb://AUDITSERVICE
          predicates:
            - Path=/audit/**
        - id: signin
          uri: lb://SIGNINSERVICE
          predicates:
            - Path=/signin/**
        - id: search
          uri: lb://SEARCHSERVICE
          predicates:
            - Path=/search
eureka:
  instance:
    instance-id: gate
    hostname: cloud-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka/