server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: static_page_route
          uri: lb://STATICHTMLSERVICE
          predicates:
            - Path=/
            - Method=GET
        - id: static_page_route
          uri: lb://STATICHTMLSERVICE
          predicates:
            - Path=/static/**
        - id: static_page_route
          uri: lb://STATICHTMLSERVICE
          predicates:
            - Path=/src/**
eureka:
  instance:
    instance-id: gate
    hostname: cloud-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka/